# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/124wzkSvJu3r-g5FWAhpM_UVNuoLA4piP
"""

print("""
     Seçeneğiniz Nedir?
     [1] Americano
     [2] Espresso
     [3] Latte
     [4] Açma
     [5] Kapatma
     
    """)
secim=int(input("Seçiminiz Nedir?  :  "))
boyut=input("Hangi boyutu seçersiniz? büyük/kücük")



if secim==1:
 if boyut:
  if boyut=="kücük":
   print("Küçük Boy Americano kahve hazırlanıyor")
  elif boyut=="büyük":
   print("Büyük Boy Americano kahve hazırlanıyor")
    
else:
   
 print("Seçiminiz Americano Kahve Hazırlanıyor")

if secim==2:
 if boyut:
  if boyut=="kücük":
    print("Küçük Boy Espresso kahve hazırlanıyor")
  elif boyut=="büyük":
     print("Büyük Boy Espresso kahve hazırlanıyor")
  

if secim==3:
 if boyut:
  if boyut=="kücük":
    print("Küçük Boy Latte kahve hazırlanıyor")
  elif boyut=="büyük":
     print("Büyük Boy Latte kahve hazırlanıyor")
  
if secim==1:
  print("ödemeniz gereken tutar 20 TL")
if secim==2:
  print("ödemeniz gereken tutar 25 TL")
if secim==3:
  print("ödemeniz gereken tutar 30 TL") 
if secim==4:
  print("Otomat Açılıyor")
if secim==5:
  print("Otomat Kapanıyor")